### ISSUE TITLE
Item data

### ISSUE THREAD

**Issue by zacherymcquade** [z16/ResourceBuilder#1]
Items dat file is corrupted. Showing nothing for items. File is the same size. The data inside shows nothing compared to original item dat files.

**Comment by z16** [comment]
So by corrupted you mean that it just didn't change?

**Comment by zacherymcquade** [comment]
Correct, https://github.com/IRedactedI/ResourceBuilder fork worked though.

**Comment by z16** [comment]
Is your installation outdated? Considering that fork is strictly behind the main repository, chances are it was forked to work with older item file formats. If so, can you try with an up to date FFXI installation, just to verify? If it works with the current DAT format, I will not be changing it - you can still work off of the other branch for your use case. If it doesn't work with current DAT files, I will fix it.

**Comment by zacherymcquade** [comment]
The FFXI ver I am currently running is Ver. 30230704_2.  I am assuming that
is the Retail Client Update - July 2023. I have no idea why the older
version worked.

**Comment by zacherymcquade** [comment]
nevermind, I recompiled it again and it started working right. No idea what
happened to be honest as all the times I been testing your source it wasn't
working and now decides it wants to work lol. Everytime I rebuilt it or
build it never gave errors so I didn't know where to start. I'll take my
issue off since its working now.

**Comment by z16** [comment]
I see. I'll look into it.

**Comment by zacherymcquade** [comment]
Your master source works. No need to spend time, it was on my end with
visual studio.
